//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace James.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frettir
    {
        public int Id { get; set; }
        public string Midill { get; set; }
        public string Fyrirsogn { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Dagsett { get; set; }
    }
}
