//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace James.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saids
    {
        public int Id { get; set; }
        public string PrimaryTopic { get; set; }
        public string GoogleSpeechText { get; set; }
        public string AnswerIntent { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
